[pytest]
DJANGO_SETTINGS_MODULE = proyecto.test_settings
python_files = test_*.py
pythonpath = backend
testpaths = backend = .
addopts = --cov=backend/cotizaciones --cov-report=term-missing --cov-report=html:coverage_report --reuse-db -x --nomigrations
