# Generated by Django 5.2.14 on 2026-07-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ciudad_nombre",
                    models.CharField(default="Río Cuarto", max_length=100),
                ),
                (
                    "latitud",
                    models.DecimalField(decimal_places=6, default=-33.13, max_digits=9),
                ),
                (
                    "longitud",
                    models.DecimalField(decimal_places=6, default=-64.35, max_digits=9),
                ),
                (
                    "empresa_nombre",
                    models.CharField(default="GCinsumos", max_length=100),
                ),
                ("empresa_direccion", models.CharField(default="", max_length=200)),
                ("empresa_telefono", models.CharField(default="", max_length=30)),
                (
                    "empresa_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Configuración",
                "db_table": "cotizaciones_configuracion",
            },
        ),
    ]
