# Generated by Django 4.2.7 on 2025-08-14 14:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Solo se permiten números."
                    )
                ],
                verbose_name="Teléfono",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Total",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacionitem",
            name="precio_unitario",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Precio Unitario",
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="telefono",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Solo se permiten números."
                    )
                ],
                verbose_name="Teléfono",
            ),
        ),
    ]
