# Generated by Django 4.2.7 on 2025-10-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0003_remove_producto_precio"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="completada",
            field=models.BooleanField(
                db_column="completado", default=False, verbose_name="Completada"
            ),
        ),
    ]
