# Generated by Django 4.2.7 on 2026-03-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0006_configuracion"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("producto", "Producto"),
                    ("servicio_soft", "Servicio (Software)"),
                    ("servicio_hard", "Servicio (Hardware)"),
                ],
                default="producto",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
