# Generated by Django 4.2.7 on 2026-05-12 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cotizaciones", "0007_producto_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionAFIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuit", models.CharField(max_length=13)),
                ("razon_social", models.CharField(max_length=255)),
                ("domicilio", models.CharField(blank=True, max_length=255)),
                ("punto_venta", models.IntegerField(default=1)),
                (
                    "ambiente",
                    models.CharField(
                        choices=[
                            ("homologacion", "Homologación (pruebas)"),
                            ("produccion", "Producción"),
                        ],
                        default="homologacion",
                        max_length=15,
                    ),
                ),
                (
                    "certificado",
                    models.FileField(blank=True, null=True, upload_to="certs/"),
                ),
                (
                    "clave_privada",
                    models.FileField(blank=True, null=True, upload_to="certs/"),
                ),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración AFIP",
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("C", "Factura C")], default="C", max_length=1
                    ),
                ),
                ("punto_venta", models.IntegerField(default=1)),
                ("numero", models.IntegerField(blank=True, null=True)),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "neto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("cae", models.CharField(blank=True, max_length=14)),
                ("cae_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("autorizada", "Autorizada por AFIP"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=10,
                    ),
                ),
                ("creada", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="cotizaciones.cliente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "ordering": ["-creada"],
            },
        ),
        migrations.CreateModel(
            name="ItemFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precio_unit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cotizaciones.factura",
                    ),
                ),
            ],
        ),
    ]
