# Generated by Django 4.2.7 on 2026-05-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0008_configuracionafip_factura_itemfactura"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracionafip",
            options={"verbose_name": "Configuración ARCA"},
        ),
        migrations.AlterField(
            model_name="factura",
            name="estado",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("autorizada", "Autorizada por ARCA"),
                    ("anulada", "Anulada"),
                ],
                default="borrador",
                max_length=10,
            ),
        ),
    ]
