# Generated by Django 4.2.30 on 2026-05-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0009_alter_configuracionafip_options_alter_factura_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cotizacion",
            name="completada",
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("enviada", "Enviada"),
                    ("aprobada", "Aprobada"),
                    ("rechazada", "Rechazada"),
                    ("facturada", "Facturada"),
                ],
                default="borrador",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
