# Generated by Django 5.2.14 on 2026-06-02 13:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0019_movimiento_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListaPrecio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje de recargo sobre el precio unitario del producto",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Porcentaje de recargo",
                    ),
                ),
                (
                    "por_defecto",
                    models.BooleanField(
                        default=False,
                        help_text="Se usará automáticamente para nuevos clientes",
                        verbose_name="Por defecto",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Lista de precio",
                "verbose_name_plural": "Listas de precio",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TiendaWebConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(default=False, verbose_name="Tienda activa"),
                ),
                (
                    "nombre_tienda",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Nombre de la tienda",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                (
                    "email_contacto",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Email de contacto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Configuración de tienda web",
                "verbose_name_plural": "Configuraciones de tienda web",
            },
        ),
    ]
