# Generated by Django 5.2.14 on 2026-06-02 13:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0020_listaprecio_tiendawebconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listaprecio",
            name="porcentaje",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Porcentaje de recargo sobre el precio unitario del producto",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Porcentaje de recargo",
            ),
        ),
        migrations.CreateModel(
            name="ListaPrecioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(max_length=200, verbose_name="Categoría"),
                ),
                ("servicio", models.CharField(max_length=500, verbose_name="Servicio")),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Precio (ARS)",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "lista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cotizaciones.listaprecio",
                        verbose_name="Lista de precio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de lista de precio",
                "verbose_name_plural": "Items de lista de precio",
                "ordering": ["orden", "categoria", "servicio"],
            },
        ),
    ]
