# Generated by Django 4.2.7 on 2025-08-22 18:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Precio",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producto",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="Stock"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="direccion",
            field=models.TextField(blank=True, null=True, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="localidad",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Localidad"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(max_length=255, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Teléfono"
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="numero",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="Número"
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Total",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacionitem",
            name="cantidad",
            field=models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="cotizacionitem",
            name="precio_unitario",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Precio Unitario",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacionitem",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Subtotal"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, null=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=255, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_unitario",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Precio Unitario",
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="contacto",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Persona de Contacto",
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="direccion",
            field=models.TextField(blank=True, null=True, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nombre",
            field=models.CharField(max_length=255, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Teléfono"
            ),
        ),
    ]
