# Generated by Django 4.2.7 on 2025-08-22 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0002_producto_precio_producto_stock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="precio",
        ),
    ]
