# Generated by Django 4.2.7 on 2026-03-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0005_cotizacion_descuento_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ciudad_nombre",
                    models.CharField(
                        default="Río Cuarto", max_length=100, verbose_name="Ciudad"
                    ),
                ),
                (
                    "latitud",
                    models.DecimalField(
                        decimal_places=6,
                        default=-33.13,
                        max_digits=9,
                        verbose_name="Latitud",
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        decimal_places=6,
                        default=-64.35,
                        max_digits=9,
                        verbose_name="Longitud",
                    ),
                ),
                (
                    "empresa_nombre",
                    models.CharField(
                        default="GCinsumos",
                        max_length=100,
                        verbose_name="Nombre empresa",
                    ),
                ),
                (
                    "empresa_direccion",
                    models.CharField(
                        default="", max_length=200, verbose_name="Dirección"
                    ),
                ),
                (
                    "empresa_telefono",
                    models.CharField(
                        default="", max_length=30, verbose_name="Teléfono"
                    ),
                ),
                (
                    "empresa_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Email empresa",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración",
                "verbose_name_plural": "Configuración",
            },
        ),
    ]
